/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.lab.student_management;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hanie
 */
public class NewStudentDialog extends javax.swing.JFrame {

    private StudentManager studentManager = new StudentManager();

    /**
     * Creates new form NewStudentDialog
     */
    public NewStudentDialog() {
        initComponents();
        setLocationRelativeTo(null);

        loadStudent(studentManager.getListStudent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupGender = new javax.swing.ButtonGroup();
        idLable = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        midNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtMidName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        yearOfBirthLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        schoolStageLable = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        txtYearOfBirth = new javax.swing.JTextField();
        cmbSchoolStage = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Student");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        idLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLable.setText("Student ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 178, 0, 0);
        getContentPane().add(idLable, gridBagConstraints);

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 68, 0, 199);
        getContentPane().add(txtStudentID, gridBagConstraints);

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 178, 0, 0);
        getContentPane().add(lastNameLabel, gridBagConstraints);

        midNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        midNameLabel.setText("Mid Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 178, 0, 0);
        getContentPane().add(midNameLabel, gridBagConstraints);

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstNameLabel.setText("Fist Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 178, 0, 0);
        getContentPane().add(firstNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 68, 0, 199);
        getContentPane().add(txtLastName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 68, 0, 199);
        getContentPane().add(txtMidName, gridBagConstraints);

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 68, 0, 199);
        getContentPane().add(txtFirstName, gridBagConstraints);

        yearOfBirthLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yearOfBirthLabel.setText("Year Of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 178, 0, 0);
        getContentPane().add(yearOfBirthLabel, gridBagConstraints);

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderLabel.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 178, 0, 0);
        getContentPane().add(genderLabel, gridBagConstraints);

        schoolStageLable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schoolStageLable.setText("School Stage");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 178, 0, 0);
        getContentPane().add(schoolStageLable, gridBagConstraints);

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 8, 77, 0);
        getContentPane().add(btnSave, gridBagConstraints);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 100, 77, 0);
        getContentPane().add(btnCancel, gridBagConstraints);

        btnGroupGender.add(rbtnMale);
        rbtnMale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnMale.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 56, 0, 0);
        getContentPane().add(rbtnMale, gridBagConstraints);

        btnGroupGender.add(rbtnFemale);
        rbtnFemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnFemale.setText("FeMale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 55, 0, 0);
        getContentPane().add(rbtnFemale, gridBagConstraints);

        txtYearOfBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearOfBirthActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 68, 0, 199);
        getContentPane().add(txtYearOfBirth, gridBagConstraints);

        cmbSchoolStage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbSchoolStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elementary School", "Middle School", "High School" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 68, 0, 0);
        getContentPane().add(cmbSchoolStage, gridBagConstraints);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 100, 77, 0);
        getContentPane().add(btnClear, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed

    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed

    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtYearOfBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearOfBirthActionPerformed

    }//GEN-LAST:event_txtYearOfBirthActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String studentID = txtStudentID.getText();
        String lastName = txtLastName.getText();
        String midName = txtMidName.getText();
        String firstName = txtFirstName.getText();
        int yearOfBirth;
        try {
            yearOfBirth = Integer.parseInt(txtYearOfBirth.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid year of birth.", "Invalid Year", JOptionPane.ERROR_MESSAGE);
            txtYearOfBirth.requestFocus();
            txtYearOfBirth.selectAll();
            return;
        }
        String gender = btnGroupGender.getSelection().getActionCommand();
        String schoolStage = cmbSchoolStage.getSelectedItem().toString();

        Student stu = new Student(studentID, lastName, midName, firstName, yearOfBirth, gender, schoolStage);

        // Use the student manager to add the new student
        if (studentManager.addStudent(stu)) {
            JOptionPane.showMessageDialog(this, "Student successfully added.");
            studentManager.getListStudent().add(stu);
            saveStudent(studentManager.getListStudent());

        } else {
            JOptionPane.showMessageDialog(this, "Student with this ID already exists.");
        }


    }//GEN-LAST:event_btnSaveActionPerformed
    protected void saveStudent(ArrayList<Student> stu) {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Student.dat"))) {
            oos.writeObject(stu);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving students to file.");
        }
    }

    protected void loadStudent(ArrayList<Student> stu) {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Student.dat"))) {
            stu = (ArrayList<Student>) ois.readObject();

        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading students from file.");
        }
    }
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Clear all text fields
        txtStudentID.setText("");
        txtLastName.setText("");
        txtMidName.setText("");
        txtFirstName.setText("");
        txtYearOfBirth.setText("");

        // Clear the selection in the gender radio buttons
        btnGroupGender.clearSelection();

        // Reset the school stage combo box to the default item
        cmbSchoolStage.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbSchoolStage;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel idLable;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel midNameLabel;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JLabel schoolStageLable;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMidName;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtYearOfBirth;
    private javax.swing.JLabel yearOfBirthLabel;
    // End of variables declaration//GEN-END:variables

}
