/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.FoodItem;
import model.FoodManager;
import model.ManageCustomer;

/**
 *
 * @author hanie
 */
public class BillFrame extends javax.swing.JDialog {

    /**
     * Creates new form BillFrame
     */
    FoodManager foodManager = new FoodManager();
    ManageCustomer manageCus = new ManageCustomer();

    public BillFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

        loadFoods();
        fillInFoodTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customersPanel1 = new javax.swing.JPanel();
        customersContentLabel1 = new javax.swing.JLabel();
        customersIDLabel = new javax.swing.JLabel();
        customersNameLabel = new javax.swing.JLabel();
        customersNameTextField = new javax.swing.JTextField();
        idComboBox = new javax.swing.JComboBox<>();
        productsPanel = new javax.swing.JPanel();
        foodContentLabel = new javax.swing.JLabel();
        foodNameLabel = new javax.swing.JLabel();
        foodNameTextField = new javax.swing.JTextField();
        foodPriceLabel = new javax.swing.JLabel();
        foodPriceTextField = new javax.swing.JTextField();
        foodQuantityLabel = new javax.swing.JLabel();
        foodQuantityTextField = new javax.swing.JTextField();
        addBillButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        foodListPanel1 = new javax.swing.JPanel();
        foodListLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        customersPanel1.setBackground(new java.awt.Color(255, 255, 255));

        customersContentLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 22)); // NOI18N
        customersContentLabel1.setForeground(new java.awt.Color(51, 0, 51));
        customersContentLabel1.setText("Customers");

        customersIDLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        customersIDLabel.setForeground(new java.awt.Color(0, 0, 204));
        customersIDLabel.setText("ID");

        customersNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        customersNameLabel.setForeground(new java.awt.Color(0, 0, 204));
        customersNameLabel.setText("Name");

        customersNameTextField.setEditable(false);
        customersNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersNameTextFieldActionPerformed(evt);
            }
        });

        idComboBox.setEditable(true);
        idComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idComboBoxItemStateChanged(evt);
            }
        });
        idComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idComboBoxMouseClicked(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customersPanel1Layout = new javax.swing.GroupLayout(customersPanel1);
        customersPanel1.setLayout(customersPanel1Layout);
        customersPanel1Layout.setHorizontalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(customersIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customersNameLabel)
                .addGap(89, 89, 89))
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(customersContentLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customersPanel1Layout.setVerticalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(customersContentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customersPanel1Layout.createSequentialGroup()
                        .addComponent(customersIDLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(customersPanel1Layout.createSequentialGroup()
                        .addComponent(customersNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))))
        );

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));

        foodContentLabel.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        foodContentLabel.setForeground(new java.awt.Color(51, 0, 51));
        foodContentLabel.setText("Food");

        foodNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodNameLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodNameLabel.setText("Name");

        foodNameTextField.setEditable(false);
        foodNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodNameTextFieldActionPerformed(evt);
            }
        });

        foodPriceLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodPriceLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodPriceLabel.setText("Price");

        foodPriceTextField.setEditable(false);
        foodPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodPriceTextFieldActionPerformed(evt);
            }
        });

        foodQuantityLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodQuantityLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodQuantityLabel.setText("Quantity");

        addBillButton.setBackground(new java.awt.Color(255, 0, 0));
        addBillButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        addBillButton.setForeground(new java.awt.Color(255, 255, 255));
        addBillButton.setText("Add to bill");
        addBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBillButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 0, 0));
        resetButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addBillButton)
                .addGap(41, 41, 41)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(foodNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foodContentLabel)
                        .addGap(140, 140, 140))
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(foodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(productsPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(foodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(foodQuantityLabel)
                                .addGap(43, 43, 43))
                            .addGroup(productsPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(foodPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(foodQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE))))))
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(foodNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBillButton)
                    .addComponent(resetButton))
                .addGap(9, 9, 9))
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        foodListPanel1.setBackground(new java.awt.Color(255, 255, 255));

        foodListLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        foodListLabel1.setForeground(new java.awt.Color(51, 0, 51));
        foodListLabel1.setText("food  List");

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Food Type", "Food Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        javax.swing.GroupLayout foodListPanel1Layout = new javax.swing.GroupLayout(foodListPanel1);
        foodListPanel1.setLayout(foodListPanel1Layout);
        foodListPanel1Layout.setHorizontalGroup(
            foodListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(foodListPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(foodListLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        foodListPanel1Layout.setVerticalGroup(
            foodListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodListPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(foodListLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        billTxtArea.setColumns(20);
        billTxtArea.setRows(5);
        jScrollPane2.setViewportView(billTxtArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(productsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(foodListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadFoods() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Foods.dat"))) {
            foodManager.setFoodList((ArrayList<FoodItem>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading Foods from file.");
        }
    }

    private void fillInFoodTable() {
        DefaultTableModel model = (DefaultTableModel) foodTable.getModel();
        int rowCount = model.getRowCount();
        // Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        // Add rows from the student list to the table model
        for (FoodItem fi : foodManager.getFoodList()) {
            Object[] row = new Object[]{
                fi.getFoodId(),
                fi.getFoodName(),
                fi.getFoodType(),
                fi.getPrice()
            };
            model.addRow(row);
        }
        pack();
    }

    private void getDataFromTable() {
        int selectedRow = foodTable.getSelectedRow();
        if (selectedRow != -1) {
            FoodItem fi = foodManager.getFoodList().get(selectedRow);

            foodNameTextField.setText(fi.getFoodName());
            foodPriceTextField.setText(String.valueOf(fi.getPrice()));

            foodNameTextField.setEditable(false);
            foodPriceTextField.setEditable(false);
        }
    }
    private void customersNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersNameTextFieldActionPerformed

    }//GEN-LAST:event_customersNameTextFieldActionPerformed

    private void idComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idComboBoxItemStateChanged

    }//GEN-LAST:event_idComboBoxItemStateChanged

    private void idComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idComboBoxMouseClicked

    }//GEN-LAST:event_idComboBoxMouseClicked

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        showNameBill();
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void foodPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodPriceTextFieldActionPerformed

    private void addBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBillButtonActionPerformed

    }//GEN-LAST:event_addBillButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed

    }//GEN-LAST:event_resetButtonActionPerformed

    private void foodNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodNameTextFieldActionPerformed

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        getDataFromTable();
    }//GEN-LAST:event_foodTableMouseClicked

    public void showNameBill() {
        String id = String.valueOf(idComboBox.getSelectedItem());
        Customer cus = manageCus.findCustomer(id);
        if (cus != null) {
            customersNameTextField.setText(cus.getCustomerName());
        } else {
            customersNameTextField.setText("");
        }

    }

    public void setIdComboBox() {
        idComboBox.removeAllItems();
        for (Customer cus : manageCus.getListCustomer()) {
            idComboBox.addItem(String.valueOf(cus.getCustomerID()));
        }
    }

    public boolean checkNumPhone(String str) {
        try {
            double number = Double.parseDouble(str);
            // Nếu không có exception, đây là một số
            return true;
        } catch (NumberFormatException e) {
            // Nếu có exception, chuỗi không phải là số
            return false;
        }
    }

    public void showFoodBill() {

    }

    public void showCus(List<Customer> listCus) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillFrame dialog = new BillFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBillButton;
    private javax.swing.JTextArea billTxtArea;
    private javax.swing.JLabel customersContentLabel1;
    private javax.swing.JLabel customersIDLabel;
    private javax.swing.JLabel customersNameLabel;
    private javax.swing.JTextField customersNameTextField;
    private javax.swing.JPanel customersPanel1;
    private javax.swing.JLabel foodContentLabel;
    private javax.swing.JLabel foodListLabel1;
    private javax.swing.JPanel foodListPanel1;
    private javax.swing.JLabel foodNameLabel;
    private javax.swing.JTextField foodNameTextField;
    private javax.swing.JLabel foodPriceLabel;
    private javax.swing.JTextField foodPriceTextField;
    private javax.swing.JLabel foodQuantityLabel;
    private javax.swing.JTextField foodQuantityTextField;
    private javax.swing.JTable foodTable;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
