/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.FoodBill;
import model.FoodItem;
import model.FoodManager;
import model.MainBill;
import model.ManageCustomer;
import model.ManageFoodBill;
import model.ManageMainBill;

/**
 *
 * @author hanie
 */
public class BillFrame extends javax.swing.JDialog {

    /**
     * Creates new form BillFrame
     */
    private FoodManager foodManager = new FoodManager();
    private ManageCustomer manageCustomer = new ManageCustomer();
    private ManageFoodBill manageFoodBill = new ManageFoodBill();
    private FoodBill foodBill = new FoodBill();
    private MainBill mainBill = new MainBill();
    private ManageMainBill manageMainBill = new ManageMainBill();

    public BillFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        loadBills();
        loadFoods();
        fillInFoodTable();

        loadCustomers();
        setIdComboBox();

        clearBill();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        customersPanel1 = new javax.swing.JPanel();
        customersContentLabel1 = new javax.swing.JLabel();
        customersIDLabel = new javax.swing.JLabel();
        customersNameLabel = new javax.swing.JLabel();
        customersNameTextField = new javax.swing.JTextField();
        idComboBox = new javax.swing.JComboBox<>();
        productsPanel = new javax.swing.JPanel();
        foodContentLabel = new javax.swing.JLabel();
        foodNameLabel = new javax.swing.JLabel();
        foodNameTextField = new javax.swing.JTextField();
        foodPriceLabel = new javax.swing.JLabel();
        foodPriceTextField = new javax.swing.JTextField();
        foodQuantityLabel = new javax.swing.JLabel();
        foodQuantityTextField = new javax.swing.JTextField();
        addBillButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        foodListPanel1 = new javax.swing.JPanel();
        foodListLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billTxtArea = new javax.swing.JTextArea();
        productBillPanel = new javax.swing.JPanel();
        productsBillLabel = new javax.swing.JLabel();
        proBillTable = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        resetBillBtn = new javax.swing.JButton();
        foodListLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);

        customersPanel1.setBackground(new java.awt.Color(255, 255, 255));

        customersContentLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 22)); // NOI18N
        customersContentLabel1.setForeground(new java.awt.Color(51, 0, 51));
        customersContentLabel1.setText("Customers");

        customersIDLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        customersIDLabel.setForeground(new java.awt.Color(0, 0, 204));
        customersIDLabel.setText("ID");

        customersNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        customersNameLabel.setForeground(new java.awt.Color(0, 0, 204));
        customersNameLabel.setText("Name");

        customersNameTextField.setEditable(false);
        customersNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersNameTextFieldActionPerformed(evt);
            }
        });

        idComboBox.setEditable(true);
        idComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idComboBoxItemStateChanged(evt);
            }
        });
        idComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idComboBoxMouseClicked(evt);
            }
        });
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customersPanel1Layout = new javax.swing.GroupLayout(customersPanel1);
        customersPanel1.setLayout(customersPanel1Layout);
        customersPanel1Layout.setHorizontalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customersPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(customersIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customersNameLabel)
                .addGap(89, 89, 89))
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(customersContentLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customersPanel1Layout.setVerticalGroup(
            customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customersPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(customersContentLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(customersPanel1Layout.createSequentialGroup()
                        .addComponent(customersIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(customersPanel1Layout.createSequentialGroup()
                        .addComponent(customersNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customersNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );

        productsPanel.setBackground(new java.awt.Color(255, 255, 255));

        foodContentLabel.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        foodContentLabel.setForeground(new java.awt.Color(51, 0, 51));
        foodContentLabel.setText("Food");

        foodNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodNameLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodNameLabel.setText("Name");

        foodNameTextField.setEditable(false);
        foodNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodNameTextFieldActionPerformed(evt);
            }
        });

        foodPriceLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodPriceLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodPriceLabel.setText("Price");

        foodPriceTextField.setEditable(false);
        foodPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodPriceTextFieldActionPerformed(evt);
            }
        });

        foodQuantityLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        foodQuantityLabel.setForeground(new java.awt.Color(0, 0, 204));
        foodQuantityLabel.setText("Quantity");

        addBillButton.setBackground(new java.awt.Color(255, 0, 0));
        addBillButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        addBillButton.setForeground(new java.awt.Color(255, 255, 255));
        addBillButton.setText("Add to bill");
        addBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBillButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 0, 0));
        resetButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(addBillButton)
                .addGap(34, 34, 34)
                .addComponent(resetButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(foodNameLabel)
                        .addGap(140, 314, Short.MAX_VALUE))
                    .addGroup(productsPanelLayout.createSequentialGroup()
                        .addComponent(foodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(productsPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foodContentLabel)
                                    .addGroup(productsPanelLayout.createSequentialGroup()
                                        .addComponent(foodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(foodQuantityLabel)))
                                .addGap(43, 43, 43))
                            .addGroup(productsPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(foodPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(foodQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(foodNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBillButton)
                    .addComponent(resetButton))
                .addGap(9, 9, 9))
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addComponent(foodContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        foodListPanel1.setBackground(new java.awt.Color(255, 255, 255));

        foodListLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        foodListLabel1.setForeground(new java.awt.Color(51, 0, 51));
        foodListLabel1.setText("food  List");

        foodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Name", "Food Type", "Food Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        foodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(foodTable);

        javax.swing.GroupLayout foodListPanel1Layout = new javax.swing.GroupLayout(foodListPanel1);
        foodListPanel1.setLayout(foodListPanel1Layout);
        foodListPanel1Layout.setHorizontalGroup(
            foodListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodListPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(foodListLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        foodListPanel1Layout.setVerticalGroup(
            foodListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodListLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        billTxtArea.setBackground(new java.awt.Color(232, 228, 228));
        billTxtArea.setColumns(20);
        billTxtArea.setRows(5);
        jScrollPane2.setViewportView(billTxtArea);

        productBillPanel.setBackground(new java.awt.Color(255, 255, 255));

        productsBillLabel.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        productsBillLabel.setForeground(new java.awt.Color(51, 0, 51));
        productsBillLabel.setText("Product Bill");

        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proBillTable.setViewportView(billTable);

        printButton.setBackground(new java.awt.Color(255, 0, 0));
        printButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        removeButton.setBackground(new java.awt.Color(255, 0, 0));
        removeButton.setFont(new java.awt.Font("VNI-Avo", 1, 14)); // NOI18N
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        amountLabel.setBackground(new java.awt.Color(0, 153, 255));
        amountLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout productBillPanelLayout = new javax.swing.GroupLayout(productBillPanel);
        productBillPanel.setLayout(productBillPanelLayout);
        productBillPanelLayout.setHorizontalGroup(
            productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                            .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                            .addComponent(productsBillLabel)
                            .addGap(125, 125, 125))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                            .addComponent(proBillTable, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)))
                    .addGroup(productBillPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(printButton)
                        .addGap(55, 55, 55)
                        .addComponent(removeButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        productBillPanelLayout.setVerticalGroup(
            productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBillPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsBillLabel)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(proBillTable, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(productBillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton)
                    .addComponent(removeButton))
                .addGap(28, 28, 28)
                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        resetBillBtn.setBackground(new java.awt.Color(255, 204, 204));
        resetBillBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetBillBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBillBtn.setText("Reset");
        resetBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBillBtnActionPerformed(evt);
            }
        });

        foodListLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 20)); // NOI18N
        foodListLabel2.setForeground(new java.awt.Color(51, 0, 51));
        foodListLabel2.setText("export biLL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetBillBtn)
                .addGap(76, 76, 76))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productBillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(foodListLabel2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(productBillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodListLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customersPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(customersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(productsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foodListPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -180;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 48, 0, 15);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customersNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersNameTextFieldActionPerformed
        showNameBill();
    }//GEN-LAST:event_customersNameTextFieldActionPerformed

    private void idComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idComboBoxItemStateChanged

    }//GEN-LAST:event_idComboBoxItemStateChanged

    private void idComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idComboBoxMouseClicked

    }//GEN-LAST:event_idComboBoxMouseClicked

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        showNameBill();
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void foodPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodPriceTextFieldActionPerformed

    private void addBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBillButtonActionPerformed
        int selectedRow = foodTable.getSelectedRow();
        if (selectedRow != -1) {
            try {
                int foodQuantity = Integer.parseInt(foodQuantityTextField.getText());
                fillInBillTable(selectedRow, foodQuantity);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter quantity as a valid integer.");
            }
        }
    }//GEN-LAST:event_addBillButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        foodNameTextField.setText("");
        foodPriceTextField.setText("");
        foodQuantityTextField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void foodNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodNameTextFieldActionPerformed

    private void foodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodTableMouseClicked
        getDataFromTable();
    }//GEN-LAST:event_foodTableMouseClicked

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int selectedRow = billTable.getSelectedRow();
        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) billTable.getModel();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item to remove.");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        fillInBill();
    }//GEN-LAST:event_printButtonActionPerformed

    private void resetBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBillBtnActionPerformed
        clearBill();
    }//GEN-LAST:event_resetBillBtnActionPerformed
    private void saveCustomers() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Customers.Dat"))) {
            oos.writeObject(manageCustomer.getListCustomer());
            //JOptionPane.showMessageDialog(this, "Customers saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving customers to file.");
        }
    }

    private void loadCustomers() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Customers.Dat"))) {
            manageCustomer.setListCustomer((ArrayList<Customer>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading customers from file.");
        }
    }

    public void saveBills() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Bills.dat"))) {
            oos.writeObject(manageMainBill.getListMainBills());
            JOptionPane.showMessageDialog(this, "Bills saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving bill to file: " + e.getMessage());
        }
    }

    public void loadBills() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Bills.dat"))) {
            manageMainBill.setListMainBills((ArrayList<MainBill>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading Bills from file.");
        }
    }

    public void saveFoods() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Foods.dat"))) {
            oos.writeObject(foodManager.getFoodList()); // Save only the ArrayList<CD>
            //JOptionPane.showMessageDialog(this, "Foods saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving Foods to file: " + e.getMessage());
        }
    }

    public void loadFoods() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Foods.dat"))) {
            foodManager.setFoodList((ArrayList<FoodItem>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading Foods from file.");
        }
    }

    private void fillInFoodTable() {
        DefaultTableModel model = (DefaultTableModel) foodTable.getModel();
        int rowCount = model.getRowCount();
        // Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        // Add rows from the student list to the table model
        for (FoodItem fi : foodManager.getFoodList()) {
            Object[] row = new Object[]{
                fi.getFoodId(),
                fi.getFoodName(),
                fi.getFoodType(),
                fi.getPrice()
            };
            model.addRow(row);
        }
        pack();
    }

    public void showNameBill() {
        String id = String.valueOf(idComboBox.getSelectedItem());
        Customer cus = manageCustomer.findCustomer(id);
        if (cus != null) {
            customersNameTextField.setText(cus.getCustomerName());
        } else {
            customersNameTextField.setText("");
        }
    }

    public void setIdComboBox() {
        idComboBox.removeAllItems();
        for (Customer cus : manageCustomer.getListCustomer()) {
            idComboBox.addItem(String.valueOf(cus.getCustomerID()));
        }
    }

    private void getDataFromTable() {
        int selectedRow = foodTable.getSelectedRow();
        if (selectedRow != -1) {
            FoodItem fi = foodManager.getFoodList().get(selectedRow);

            foodNameTextField.setText(fi.getFoodName());
            foodPriceTextField.setText(String.valueOf(fi.getPrice()));

            foodNameTextField.setEditable(false);
            foodPriceTextField.setEditable(false);
        }
    }

    private void fillInBillTable(int selectedRow, int foodQuantity) {
        FoodItem fi = foodManager.getFoodList().get(selectedRow);
        String foodName = fi.getFoodName();
        double foodPrice = fi.getPrice();
        double totalPrice;

        if (foodQuantity <= 0 || foodQuantity > fi.getQuantity()) {
            JOptionPane.showMessageDialog(this, "Not enough quantity to supply. Quantity currently available: " + fi.getQuantity());
            return;
        }

        totalPrice = foodPrice * foodQuantity;

        FoodBill fooBi = new FoodBill(foodName, foodPrice, foodQuantity, totalPrice);
        manageFoodBill.getBills().add(fooBi);

        // Trừ số lượng và cập nhật vào FoodManager
        fi.setQuantity(fi.getQuantity() - foodQuantity);
        saveFoods();

        // Thêm vào bảng hóa đơn
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.addRow(new Object[]{foodName, foodPrice, foodQuantity, totalPrice});
    }

    public void fillInBill() {
        try {
            DecimalFormat df = new DecimalFormat("#,##0.00");
            LocalDateTime dateTime = LocalDateTime.now();
            String customerId = idComboBox.getSelectedItem().toString();
            String customerName = customersNameTextField.getText();
            ArrayList<FoodBill> items = manageFoodBill.getBills();
            float grandTotal = 0;

            for (FoodBill item : items) {
                grandTotal += item.getTotalPrice();
            }

            MainBill mBill = new MainBill(dateTime, customerId, customerName, items, grandTotal);

            String billText = mBill.generateBillText(df);
            billTxtArea.setText(billText);

            manageMainBill.getListMainBills().add(mBill);

            saveBills();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "An error occurred due to null data: " + e.getMessage(), "Data Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearBill() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String header = "\t" + dateFormat.format(date) + "\n"
                + "===============ANNA RESTAURANT=================\n"
                + "Food Name\tQuantity\tPrice\tTotal Price\n"
                + "--------------------------------------------------\n";

        billTxtArea.setText(header);

        customersNameTextField.setText("");
        idComboBox.setSelectedIndex(-1);

        manageFoodBill.getBills().clear();

        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillFrame dialog = new BillFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBillButton;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTable billTable;
    private javax.swing.JTextArea billTxtArea;
    private javax.swing.JLabel customersContentLabel1;
    private javax.swing.JLabel customersIDLabel;
    private javax.swing.JLabel customersNameLabel;
    private javax.swing.JTextField customersNameTextField;
    private javax.swing.JPanel customersPanel1;
    private javax.swing.JLabel foodContentLabel;
    private javax.swing.JLabel foodListLabel1;
    private javax.swing.JLabel foodListLabel2;
    private javax.swing.JPanel foodListPanel1;
    private javax.swing.JLabel foodNameLabel;
    private javax.swing.JTextField foodNameTextField;
    private javax.swing.JLabel foodPriceLabel;
    private javax.swing.JTextField foodPriceTextField;
    private javax.swing.JLabel foodQuantityLabel;
    private javax.swing.JTextField foodQuantityTextField;
    private javax.swing.JTable foodTable;
    private javax.swing.JComboBox<String> idComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton printButton;
    private javax.swing.JScrollPane proBillTable;
    private javax.swing.JPanel productBillPanel;
    private javax.swing.JLabel productsBillLabel;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton resetBillBtn;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
