/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.lab._22_01;

import javax.swing.JOptionPane;

/**
 *
 * @author hanie
 */
public class PetServiceTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form PetServiceTicketFrame
     */
    public PetServiceTicketFrame() {
        initComponents();
        setLocationRelativeTo(null);

        ticketInfoTxtArea.setEditable(false);
        generalCheckbox.setSelected(true);
        generalCheckbox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        fillPanel = new javax.swing.JPanel();
        ticketIdLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        basePriceLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        ticketIdTxt = new javax.swing.JTextField();
        customerNameTxt = new javax.swing.JTextField();
        basePriceTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        petTypeLabel = new javax.swing.JLabel();
        dogRadioBtn = new javax.swing.JRadioButton();
        catRadioBtn = new javax.swing.JRadioButton();
        petSizeLabel = new javax.swing.JLabel();
        petSizeCmb = new javax.swing.JComboBox<>();
        voucherLabel = new javax.swing.JLabel();
        voucherTxt = new javax.swing.JTextField();
        servicesLabel = new javax.swing.JLabel();
        generalCheckbox = new javax.swing.JCheckBox();
        washingCheckbox = new javax.swing.JCheckBox();
        groomingCheckbox = new javax.swing.JCheckBox();
        clippingCheckbox = new javax.swing.JCheckBox();
        brushingCheckbox = new javax.swing.JCheckBox();
        printBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        ticketInformationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketInfoTxtArea = new javax.swing.JTextArea();
        ticketInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ticketIdLabel.setText("Ticket ID");

        customerNameLabel.setText("Customer Name");

        basePriceLabel.setText("Base Price");

        phoneLabel.setText("Phone");

        petTypeLabel.setText("Pet type");

        buttonGroup.add(dogRadioBtn);
        dogRadioBtn.setText("Dog");

        buttonGroup.add(catRadioBtn);
        catRadioBtn.setText("Cat");
        catRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadioBtnActionPerformed(evt);
            }
        });

        petSizeLabel.setText("Pet size");

        petSizeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", "Extra Large", " " }));

        voucherLabel.setText("Voucher");

        servicesLabel.setText("Services:");

        generalCheckbox.setText("General Check");

        washingCheckbox.setText("Washing");

        groomingCheckbox.setText("Grooming");

        clippingCheckbox.setText("Clipping");
        clippingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clippingCheckboxActionPerformed(evt);
            }
        });

        brushingCheckbox.setText("Brushing");
        brushingCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brushingCheckboxActionPerformed(evt);
            }
        });

        printBtn.setText("Print Ticket");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fillPanelLayout = new javax.swing.GroupLayout(fillPanel);
        fillPanel.setLayout(fillPanelLayout);
        fillPanelLayout.setHorizontalGroup(
            fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fillPanelLayout.createSequentialGroup()
                        .addComponent(ticketIdLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fillPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(washingCheckbox)
                        .addGap(142, 142, 142)
                        .addComponent(groomingCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(fillPanelLayout.createSequentialGroup()
                        .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(fillPanelLayout.createSequentialGroup()
                                    .addComponent(clippingCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(142, 142, 142)
                                    .addComponent(brushingCheckbox))
                                .addGroup(fillPanelLayout.createSequentialGroup()
                                    .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(fillPanelLayout.createSequentialGroup()
                                            .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(petSizeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(voucherLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(servicesLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(fillPanelLayout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(generalCheckbox))
                                                .addGroup(fillPanelLayout.createSequentialGroup()
                                                    .addGap(54, 54, 54)
                                                    .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(catRadioBtn)
                                                        .addComponent(voucherTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(fillPanelLayout.createSequentialGroup()
                                                    .addGap(54, 54, 54)
                                                    .addComponent(petSizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(fillPanelLayout.createSequentialGroup()
                                            .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(customerNameLabel)
                                                .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(basePriceLabel)
                                                .addComponent(petTypeLabel))
                                            .addGap(22, 22, 22)
                                            .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ticketIdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                .addComponent(customerNameTxt)
                                                .addComponent(phoneTxt)
                                                .addComponent(dogRadioBtn)
                                                .addComponent(basePriceTxt)))
                                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(13, 13, 13)))
                            .addGroup(fillPanelLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(clearBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        fillPanelLayout.setVerticalGroup(
            fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIdLabel)
                    .addComponent(ticketIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basePriceLabel))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petTypeLabel)
                    .addComponent(dogRadioBtn)
                    .addComponent(catRadioBtn))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petSizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voucherLabel)
                    .addComponent(voucherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servicesLabel)
                    .addComponent(generalCheckbox))
                .addGap(18, 18, 18)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(washingCheckbox)
                    .addComponent(groomingCheckbox))
                .addGap(26, 26, 26)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clippingCheckbox)
                    .addComponent(brushingCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(fillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printBtn)
                    .addComponent(clearBtn))
                .addGap(21, 21, 21))
        );

        ticketInfoTxtArea.setColumns(20);
        ticketInfoTxtArea.setRows(5);
        jScrollPane1.setViewportView(ticketInfoTxtArea);

        ticketInformationLabel.setText("Ticket Information");

        javax.swing.GroupLayout ticketInformationPanelLayout = new javax.swing.GroupLayout(ticketInformationPanel);
        ticketInformationPanel.setLayout(ticketInformationPanelLayout);
        ticketInformationPanelLayout.setHorizontalGroup(
            ticketInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketInformationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(ticketInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketInformationLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ticketInformationPanelLayout.setVerticalGroup(
            ticketInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ticketInformationPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ticketInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(fillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catRadioBtnActionPerformed

    private void clippingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clippingCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clippingCheckboxActionPerformed

    private void brushingCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brushingCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brushingCheckboxActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        if (!isFill()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }

        try {
            int ticketID = Integer.parseInt(ticketIdTxt.getText());
            float basePrice = Float.parseFloat(basePriceTxt.getText());
            float voucher = Float.parseFloat(voucherTxt.getText());

            String customerName = customerNameTxt.getText();
            String phone = phoneTxt.getText();

            String petType = getPetType();
            String petSize = getPetSize();
            String services = getServices();

            PetServicesTicket ticket = new PetServicesTicket(ticketID, customerName, phone, petType, petSize, basePrice, services, voucher);
            float payment = ticket.getPayment();

            ticketInfoTxtArea.setText(buildTicketInfo(ticketID, customerName, phone, petType, petSize, payment, services));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Check your numbers!");
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearForm();
    }//GEN-LAST:event_clearBtnActionPerformed
    private String getServices() {
        StringBuilder services = new StringBuilder();

        if (generalCheckbox.isSelected()) {
            services.append("General Check, ");
        }
        if (washingCheckbox.isSelected()) {
            services.append("Washing, ");
        }
        if (groomingCheckbox.isSelected()) {
            services.append("Grooming, ");
        }
        if (clippingCheckbox.isSelected()) {
            services.append("Clipping, ");
        }
        if (brushingCheckbox.isSelected()) {
            services.append("Brushing, ");
        }

        if (services.length() > 0) {
            services.setLength(services.length() - 2);
        }

        return services.toString();
    }

    private String getPetSize() {
        return petSizeCmb.getSelectedItem().toString();
    }

    private String getPetType() {
        if (dogRadioBtn.isSelected()) {
            return "Dog";
        } else if (catRadioBtn.isSelected()) {
            return "Cat";
        }
        return "";
    }

    private boolean isFill() {
        return !(ticketIdTxt.getText().trim().isEmpty()
                || customerNameTxt.getText().trim().isEmpty()
                || phoneTxt.getText().trim().isEmpty()
                || basePriceTxt.getText().trim().isEmpty()
                || voucherTxt.getText().trim().isEmpty());
    }

    private String buildTicketInfo(int ticketID, String customerName, String phoneNumber, String type, String size, float payment, String services) {
        return "Ticket ID: " + ticketID + "\n"
                + "Customer: " + customerName + "\n"
                + "Phone: " + phoneNumber + "\n"
                + "Type: " + type + "\n"
                + "Size: " + size + "\n"
                + "Services: " + services + "\n"
                + "-----*-----Payment: " + "\t" + payment;
    }

    private void clearForm() {
        ticketIdTxt.setText("");
        customerNameTxt.setText("");
        phoneTxt.setText("");
        basePriceTxt.setText("");
        voucherTxt.setText("");
        buttonGroup.clearSelection();
        petSizeCmb.setSelectedIndex(0);
        generalCheckbox.setSelected(true);
        washingCheckbox.setSelected(false);
        groomingCheckbox.setSelected(false);
        clippingCheckbox.setSelected(false);
        brushingCheckbox.setSelected(false);
        ticketInfoTxtArea.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetServiceTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetServiceTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetServiceTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetServiceTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetServiceTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basePriceLabel;
    private javax.swing.JTextField basePriceTxt;
    private javax.swing.JCheckBox brushingCheckbox;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton catRadioBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JCheckBox clippingCheckbox;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JRadioButton dogRadioBtn;
    private javax.swing.JPanel fillPanel;
    private javax.swing.JCheckBox generalCheckbox;
    private javax.swing.JCheckBox groomingCheckbox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> petSizeCmb;
    private javax.swing.JLabel petSizeLabel;
    private javax.swing.JLabel petTypeLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JLabel ticketIdLabel;
    private javax.swing.JTextField ticketIdTxt;
    private javax.swing.JTextArea ticketInfoTxtArea;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JPanel ticketInformationPanel;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JTextField voucherTxt;
    private javax.swing.JCheckBox washingCheckbox;
    // End of variables declaration//GEN-END:variables
}
