/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author maianhtran
 */
public class RevenueFrame extends javax.swing.JDialog {

    /**
     * Creates new form RevenueFrame
     */
    private ManageMainBill manageMainBill = new ManageMainBill();

    public RevenueFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        revenueTable.setDefaultEditor(Object.class, null);

        loadBills();
        setDateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        revenueTable = new javax.swing.JTable();
        endDateComboBox = new javax.swing.JComboBox<>();
        endDateLabel = new javax.swing.JLabel();
        startDateComboBox = new javax.swing.JComboBox<>();
        startDateLabel = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(183, 229, 215));

        jPanel1.setBackground(new java.awt.Color(183, 229, 215));

        revenueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Date", "Customer Name", "Food Quantity", "Bill"
            }
        ));
        jScrollPane1.setViewportView(revenueTable);

        endDateComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 139, 221), 3, true));
        endDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateComboBoxActionPerformed(evt);
            }
        });

        endDateLabel.setBackground(new java.awt.Color(138, 138, 219));
        endDateLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        endDateLabel.setForeground(new java.awt.Color(138, 138, 219));
        endDateLabel.setText("End Date");

        startDateComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 139, 221), 3, true));
        startDateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateComboBoxActionPerformed(evt);
            }
        });

        startDateLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(138, 138, 219));
        startDateLabel.setText("Start Date");

        totalField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 139, 221), 3, true));

        totalLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(138, 138, 219));
        totalLabel.setText("Total");

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        searchBT.setBackground(new java.awt.Color(0, 153, 153));
        searchBT.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchBT.setForeground(new java.awt.Color(255, 255, 255));
        searchBT.setText("Search");
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(696, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addGap(37, 37, 37)
                        .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(startDateLabel)
                                        .addGap(342, 342, 342)
                                        .addComponent(endDateLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(startDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(endDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(searchBT)))))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel)
                    .addComponent(startDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateComboBoxActionPerformed

    }//GEN-LAST:event_startDateComboBoxActionPerformed

    private void endDateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateComboBoxActionPerformed

    }//GEN-LAST:event_endDateComboBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_searchBTActionPerformed

    /**
     * @param args the command line arguments
     */
    private void updateTable() {
        LocalDateTime start = LocalDateTime.parse(startDateComboBox.getSelectedItem().toString());
        LocalDateTime end = LocalDateTime.parse(endDateComboBox.getSelectedItem().toString());

        setTable(start, end);
    }

    public void setTable(LocalDateTime start, LocalDateTime end) {
        DefaultTableModel model = (DefaultTableModel) revenueTable.getModel();
        model.setRowCount(0);

        float totalRevenue = 0;

        for (MainBill bill : manageMainBill.getListMainBills()) {
            LocalDateTime billDate = bill.getDateTime();
            if (!billDate.isBefore(start) && !billDate.isAfter(end)) {
                String customerName = bill.getCustomerName();
                float grandTotal = bill.getGrandTotal();
                int quantity = 0;
                for (FoodBill f : bill.getItems()) {
                    quantity += f.getOrderQuantity();
                }

                totalRevenue += grandTotal;

                Object[] rows = new Object[]{billDate.toLocalDate(), customerName, quantity, grandTotal};
                model.addRow(rows);
            } else if (billDate.toLocalDate().isEqual(LocalDate.now())) {
                String customerName = bill.getCustomerName();

                float grandTotal = bill.getGrandTotal();
                int quantity = 0;
                for (FoodBill f : bill.getItems()) {
                    quantity += f.getOrderQuantity();
                }
            }

            totalField.setText(String.format("%.2f", totalRevenue));

            pack();
        }
    }

    public void setDateComboBox() {
        startDateComboBox.removeAllItems();
        endDateComboBox.removeAllItems();
        for (MainBill m : manageMainBill.getListMainBills()) {
            startDateComboBox.addItem(String.valueOf(m.getDateTime()));
            endDateComboBox.addItem(String.valueOf(m.getDateTime()));

        }

    }

    public void saveBills() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Bills.dat"))) {
            oos.writeObject(manageMainBill.getListMainBills());
            JOptionPane.showMessageDialog(this, "Bills saved successfully!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving bill to file: " + e.getMessage());
        }
    }

    public void loadBills() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Bills.dat"))) {
            manageMainBill.setListMainBills((ArrayList<MainBill>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading Bills from file.");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevenueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevenueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevenueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevenueFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RevenueFrame dialog = new RevenueFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> endDateComboBox;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable revenueTable;
    private javax.swing.JButton searchBT;
    private javax.swing.JComboBox<String> startDateComboBox;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
