/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.lab._23_02_111;

import javax.swing.JOptionPane;

/**
 *
 * @author hanie
 */
public class TicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form TicketFrame
     */
    public TicketFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        ticketInfoTxtArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        fillPanel = new javax.swing.JPanel();
        ticketIdLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        licensePlatesLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        ticketIdTxt = new javax.swing.JTextField();
        customerNameTxt = new javax.swing.JTextField();
        licensePlatesTxt = new javax.swing.JTextField();
        customerIdTxt = new javax.swing.JTextField();
        motorcycleTypeLabel = new javax.swing.JLabel();
        motorcycleTypeCmb = new javax.swing.JComboBox<>();
        voucherLabel = new javax.swing.JLabel();
        voucherTxt = new javax.swing.JTextField();
        extraPackageLabel = new javax.swing.JLabel();
        helmetCheckbox = new javax.swing.JCheckBox();
        suiteCheckbox = new javax.swing.JCheckBox();
        cargoBoxCheckbox = new javax.swing.JCheckBox();
        printBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        noOfDayLabel = new javax.swing.JLabel();
        noOfDayTxt = new javax.swing.JTextField();
        ticketInformationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketInfoTxtArea = new javax.swing.JTextArea();
        ticketInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        fillPanel.setLayout(new java.awt.GridBagLayout());

        ticketIdLabel.setText("Ticket ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        fillPanel.add(ticketIdLabel, gridBagConstraints);

        customerNameLabel.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(customerNameLabel, gridBagConstraints);

        licensePlatesLabel.setText("License Plates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(licensePlatesLabel, gridBagConstraints);

        customerIdLabel.setText("Customer ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        fillPanel.add(customerIdLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        fillPanel.add(ticketIdTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(customerNameTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(licensePlatesTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(customerIdTxt, gridBagConstraints);

        motorcycleTypeLabel.setText("Motorcycle Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(motorcycleTypeLabel, gridBagConstraints);

        motorcycleTypeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scooter", "Naked Bike", "Adventure Bike", "Cruiser", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(motorcycleTypeCmb, gridBagConstraints);

        voucherLabel.setText("Voucher");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(voucherLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(voucherTxt, gridBagConstraints);

        extraPackageLabel.setText("Extra Package");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 18, 0, 0);
        fillPanel.add(extraPackageLabel, gridBagConstraints);

        helmetCheckbox.setText("Helmet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 4, 0, 0);
        fillPanel.add(helmetCheckbox, gridBagConstraints);

        suiteCheckbox.setText("Suite");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 0, 0);
        fillPanel.add(suiteCheckbox, gridBagConstraints);

        cargoBoxCheckbox.setText("Cargo Box");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 31, 0, 3);
        fillPanel.add(cargoBoxCheckbox, gridBagConstraints);

        printBtn.setText("Print Ticket");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 13, 0);
        fillPanel.add(printBtn, gridBagConstraints);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 13, 0);
        fillPanel.add(clearBtn, gridBagConstraints);

        noOfDayLabel.setText("No Of Day");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 18, 0, 0);
        fillPanel.add(noOfDayLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 4, 0, 0);
        fillPanel.add(noOfDayTxt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(fillPanel, gridBagConstraints);

        ticketInformationPanel.setLayout(new java.awt.GridBagLayout());

        ticketInfoTxtArea.setColumns(20);
        ticketInfoTxtArea.setRows(5);
        jScrollPane1.setViewportView(ticketInfoTxtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 359;
        gridBagConstraints.ipady = 367;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 7, 5);
        ticketInformationPanel.add(jScrollPane1, gridBagConstraints);

        ticketInformationLabel.setText("Ticket Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        ticketInformationPanel.add(ticketInformationLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -198;
        gridBagConstraints.ipady = -70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 0);
        jPanel1.add(ticketInformationPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        
        if (!isFill()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }
        
        try {
            int ticketId = Integer.parseInt(ticketIdTxt.getText());
            int noOfDay = Integer.parseInt(noOfDayTxt.getText());
            float voucher = Float.parseFloat(voucherTxt.getText());
            
            String customerName = customerNameTxt.getText();
            String customerId = customerIdTxt.getText();
            String licensePlates = licensePlatesTxt.getText();
            
            String motorcycleType = getMotorType();
            String extraPackage = getExtra();
            
            MotorcycleRentalTicket ticket = new MotorcycleRentalTicket(ticketId, customerName, customerId, licensePlates, motorcycleType, noOfDay, extraPackage, voucher);
            
            float payment = ticket.getPayment();
            
            ticketInfoTxtArea.setText(buildTicketForm(ticketId, customerName, customerId, licensePlates, noOfDay, motorcycleType, extraPackage, payment));
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please check your numbers");
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearForm();
    }//GEN-LAST:event_clearBtnActionPerformed
    
    private String getExtra() {
        StringBuilder extra = new StringBuilder();
        
        if (helmetCheckbox.isSelected()) {
            extra.append("Helmet, ");
        }
        if (suiteCheckbox.isSelected()) {
            extra.append("Suite, ");
        }
        if (cargoBoxCheckbox.isSelected()) {
            extra.append("Cargo Box, ");
        }
        
        if (extra.length() > 0) {
            extra.setLength(extra.length() - 2);
        }
        
        return extra.toString();
    }
    
    private String getMotorType() {
        return motorcycleTypeCmb.getSelectedItem().toString();
    }
    
    private String buildTicketForm(int ticketId, String customerName, String customerId, String licensePlates, int noOfDay, String motorcycleType, String extraPackage, float payment) {
        
        return "Ticket ID: " + ticketId + "\n"
                + "Customer Name: " + customerName + "\n"
                + "Customer ID: " + customerId + "\n"
                + "License Plates: " + licensePlates + "\n"
                + "No Of Day: " + noOfDay + "\n"
                + "Motor Type: " + motorcycleType + "\n"
                + "Extra Package: " + extraPackage + "\n"
                + "-----*-----Payment: " + payment;
    }
    
    private boolean isFill() {
        if (ticketIdTxt.getText().trim().isEmpty()
                || customerNameTxt.getText().trim().isEmpty()
                || customerIdTxt.getText().trim().isEmpty()
                || licensePlatesTxt.getText().trim().isEmpty()
                || noOfDayTxt.getText().trim().isEmpty()
                || voucherTxt.getText().trim().isEmpty()) {
            return false;
        }
        return true;
    }
    
    private void clearForm() {
        ticketIdTxt.setText("");
        customerNameTxt.setText("");
        customerIdTxt.setText("");
        licensePlatesTxt.setText("");
        noOfDayTxt.setText("");
        motorcycleTypeCmb.setSelectedIndex(0);
        helmetCheckbox.setSelected(false);
        suiteCheckbox.setSelected(false);
        cargoBoxCheckbox.setSelected(false);
        voucherTxt.setText("");
        ticketInfoTxtArea.setText("");
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cargoBoxCheckbox;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdTxt;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JLabel extraPackageLabel;
    private javax.swing.JPanel fillPanel;
    private javax.swing.JCheckBox helmetCheckbox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel licensePlatesLabel;
    private javax.swing.JTextField licensePlatesTxt;
    private javax.swing.JComboBox<String> motorcycleTypeCmb;
    private javax.swing.JLabel motorcycleTypeLabel;
    private javax.swing.JLabel noOfDayLabel;
    private javax.swing.JTextField noOfDayTxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JCheckBox suiteCheckbox;
    private javax.swing.JLabel ticketIdLabel;
    private javax.swing.JTextField ticketIdTxt;
    private javax.swing.JTextArea ticketInfoTxtArea;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JPanel ticketInformationPanel;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JTextField voucherTxt;
    // End of variables declaration//GEN-END:variables
}
