/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.io.FileInputStream;

import java.io.IOException;
import java.io.ObjectInputStream;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import model.ManageOwner;
import model.Owner;

public class Login extends javax.swing.JFrame {

    private ManageOwner manageOwner = new ManageOwner();

    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

        loadOwners();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        showRBT = new javax.swing.JRadioButton();
        loginBT = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        signInLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        registerBT = new javax.swing.JButton();
        helloLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        helloLabel1 = new javax.swing.JLabel();
        helloLabel2 = new javax.swing.JLabel();
        signInIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(185, 232, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 160, 286, 34));
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 240, 286, 36));

        showRBT.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        showRBT.setForeground(new java.awt.Color(139, 139, 221));
        showRBT.setText("Show password");
        showRBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRBTActionPerformed(evt);
            }
        });
        jPanel1.add(showRBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 288, -1, -1));

        loginBT.setBackground(new java.awt.Color(0, 153, 153));
        loginBT.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        loginBT.setForeground(new java.awt.Color(255, 255, 255));
        loginBT.setText("Sign In");
        loginBT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTActionPerformed(evt);
            }
        });
        jPanel1.add(loginBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 395, 207, 35));

        usernameLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(139, 139, 221));
        usernameLabel.setText("Username:");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 131, 85, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(139, 139, 221));
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 212, 85, -1));

        signInLabel.setBackground(new java.awt.Color(255, 255, 255));
        signInLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        signInLabel.setForeground(new java.awt.Color(255, 255, 255));
        signInLabel.setText("Sign In");
        jPanel1.add(signInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 37, -1, 54));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("____________________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 97, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        jPanel3.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(181, 181, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerBT.setBackground(new java.awt.Color(0, 153, 153));
        registerBT.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        registerBT.setForeground(new java.awt.Color(255, 255, 255));
        registerBT.setText("Sign Up");
        registerBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBTActionPerformed(evt);
            }
        });
        jPanel2.add(registerBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 217, 35));

        helloLabel.setBackground(new java.awt.Color(255, 255, 255));
        helloLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel.setText("Hello, Friend!");
        jPanel2.add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 55));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("____________________________________________________");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        helloLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        helloLabel1.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel1.setText("Please register your account ");
        jPanel2.add(helloLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        helloLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        helloLabel2.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel2.setText("and start journey with us !");
        jPanel2.add(helloLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel2.add(signInIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 148, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hanie\\OneDrive\\Desktop\\Ky-thuat-phan-mem\\CSE_203_OOP_23_24\\TMAnh_PNHNhi_Project_Restaurant_Management_System\\src\\main\\java\\image\\food.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, 150));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private void loadCustomers() {
//        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Customers.Dat"))) {
//            manageCustomer.setListCustomer((ArrayList<Customer>) ois.readObject());
//        } catch (IOException | ClassNotFoundException e) {
//            JOptionPane.showMessageDialog(this, "Error loading customers from file.");
//        }
//    }
    private void loadOwners() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Owners.Dat"))) {
            manageOwner.setListOwner((ArrayList<Owner>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading owners from file.");
        }
    }


    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void loginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTActionPerformed
        if (usernameTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username can not be empty");
            usernameTF.requestFocus();
            return;
        } else if (usernameTF.getText().contains(" ")) {
            JOptionPane.showMessageDialog(this, "Username can not contain space");
            usernameTF.requestFocus();
            return;
        } else if (passwordTF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password can not be empty");
            passwordTF.requestFocus();
            return;
        } else {
            if (checkUsername()) {
                if (checkPassword()) {
                    JOptionPane.showMessageDialog(this, "Login successfully");
                    new MainForm().setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Password");
                    passwordTF.requestFocus();
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Username");
                usernameTF.requestFocus();
                return;
            }
        }
    }//GEN-LAST:event_loginBTActionPerformed

    private void registerBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBTActionPerformed
        new Register(manageOwner).setVisible(true);
    }//GEN-LAST:event_registerBTActionPerformed

    private void showRBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRBTActionPerformed
        if (showRBT.isSelected()) {
            passwordTF.setEchoChar((char) 0);
        } else {
            passwordTF.setEchoChar('*');
        }
    }//GEN-LAST:event_showRBTActionPerformed

    private boolean checkUsername() {
        for (Owner owner : manageOwner.getListOwner()) {
            if (owner.getUsername().equals(usernameTF.getText().trim())) {
                return true;
            }
        }
        return false;
    }

    private boolean checkPassword() {
        for (Owner owner : manageOwner.getListOwner()) {
            if (owner.getUsername().equals(usernameTF.getText().trim()) && owner.getPassword().equals(passwordTF.getText().trim())) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel helloLabel1;
    private javax.swing.JLabel helloLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBT;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton registerBT;
    private javax.swing.JRadioButton showRBT;
    private javax.swing.JLabel signInIcon;
    private javax.swing.JLabel signInLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
