/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.lab._22_02;

import javax.swing.JOptionPane;

/**
 *
 * @author hanie
 */
public class ShoesServicesTicketFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShoesServicesTicketFrame
     */
    public ShoesServicesTicketFrame() {
        initComponents();
        setLocationRelativeTo(null);

        ticketInfoTxtArea.setEditable(false);
        washingCheckbox.setSelected(true);
        washingCheckbox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        fillPanel = new javax.swing.JPanel();
        ticketIdLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        ticketIdTxt = new javax.swing.JTextField();
        customerNameTxt = new javax.swing.JTextField();
        modelTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        laborPriceLabel = new javax.swing.JLabel();
        voucherLabel = new javax.swing.JLabel();
        voucherTxt = new javax.swing.JTextField();
        servicesLabel = new javax.swing.JLabel();
        renewUpperCheckbox = new javax.swing.JCheckBox();
        washingCheckbox = new javax.swing.JCheckBox();
        renewSoleCheckbox = new javax.swing.JCheckBox();
        repairCheckbox = new javax.swing.JCheckBox();
        customPaintCheckbox = new javax.swing.JCheckBox();
        printBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        laborPriceTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeCmb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ticketInformationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketInfoTxtArea = new javax.swing.JTextArea();
        ticketInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fillPanel.setLayout(new java.awt.GridBagLayout());

        ticketIdLabel.setText("Ticket ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        fillPanel.add(ticketIdLabel, gridBagConstraints);

        customerNameLabel.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(customerNameLabel, gridBagConstraints);

        modelLabel.setText("Model");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(modelLabel, gridBagConstraints);

        brandLabel.setText("Brand");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        fillPanel.add(brandLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        fillPanel.add(ticketIdTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(customerNameTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(modelTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(brandTxt, gridBagConstraints);

        laborPriceLabel.setText("Labor Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        fillPanel.add(laborPriceLabel, gridBagConstraints);

        voucherLabel.setText("Voucher");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 0);
        fillPanel.add(voucherLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        fillPanel.add(voucherTxt, gridBagConstraints);

        servicesLabel.setText("Services:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 18, 0, 0);
        fillPanel.add(servicesLabel, gridBagConstraints);

        renewUpperCheckbox.setText("Renew Upper");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        fillPanel.add(renewUpperCheckbox, gridBagConstraints);

        washingCheckbox.setText("Washing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 0, 0);
        fillPanel.add(washingCheckbox, gridBagConstraints);

        renewSoleCheckbox.setText("Renew Sole");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        fillPanel.add(renewSoleCheckbox, gridBagConstraints);

        repairCheckbox.setText("Repair");
        repairCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repairCheckboxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        fillPanel.add(repairCheckbox, gridBagConstraints);

        customPaintCheckbox.setText("Custom Paint");
        customPaintCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPaintCheckboxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 6);
        fillPanel.add(customPaintCheckbox, gridBagConstraints);

        printBtn.setText("Print Ticket");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 19, 0);
        fillPanel.add(printBtn, gridBagConstraints);

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 14, 19, 6);
        fillPanel.add(clearBtn, gridBagConstraints);

        colorLabel.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 18, 0, 0);
        fillPanel.add(colorLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 0, 0);
        fillPanel.add(laborPriceTxt, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 4, 0, 0);
        fillPanel.add(colorTxt, gridBagConstraints);

        typeLabel.setText("Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        fillPanel.add(typeLabel, gridBagConstraints);

        typeCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandals", "Sneakers", "Leather Shoes", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        fillPanel.add(typeCmb, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(fillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        ticketInformationPanel.setLayout(new java.awt.GridBagLayout());

        ticketInfoTxtArea.setColumns(20);
        ticketInfoTxtArea.setRows(5);
        jScrollPane1.setViewportView(ticketInfoTxtArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 359;
        gridBagConstraints.ipady = 414;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 5);
        ticketInformationPanel.add(jScrollPane1, gridBagConstraints);

        ticketInformationLabel.setText("Ticket Information");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        ticketInformationPanel.add(ticketInformationLabel, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 6, 40);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repairCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repairCheckboxActionPerformed

    }//GEN-LAST:event_repairCheckboxActionPerformed

    private void customPaintCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPaintCheckboxActionPerformed

    }//GEN-LAST:event_customPaintCheckboxActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed

        if (!isFill()) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
            return;
        }

        try {
            int ticketId = Integer.parseInt(ticketIdTxt.getText());
            float laborPrice = Float.parseFloat(laborPriceTxt.getText());
            float voucher = Float.parseFloat(voucherTxt.getText());

            String customerName = customerNameTxt.getText();
            String brand = brandTxt.getText();
            String model = modelTxt.getText();
            String color = colorTxt.getText();

            String type = getShoesType();
            String services = getShoesServices();

            ShoesServicesTicket ticket = new ShoesServicesTicket(ticketId, customerName, brand, model, color, type, laborPrice, services, voucher);

            float payment = ticket.getPayment();

            ticketInfoTxtArea.setText(buildTicketForm(ticketId, customerName, brand, model, type, color, services, payment));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please check your numbbers!");
        }
    }//GEN-LAST:event_printBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearForm();
    }//GEN-LAST:event_clearBtnActionPerformed

    private String buildTicketForm(int ticketId, String customerName, String brand, String model, String type, String color, String services, float payment) {
        return "Ticket ID: \t" + ticketId + "\n"
                + "Customer Name: \t" + customerName + "\n"
                + "Brand: \t" + brand + "\n"
                + "Model: \t" + model + "\n"
                + "Type: \t" + type + "\n"
                + "Color: \t" + color + "\n"
                + "Services: \t" + services + "\n"
                + "-----*-----Payment: \t" + payment + "\n";
    }

    private String getShoesServices() {
        StringBuilder services = new StringBuilder();

        if (washingCheckbox.isSelected()) {
            services.append("Washing, ");
        }
        if (renewUpperCheckbox.isSelected()) {
            services.append("Renew Upper, ");
        }
        if (renewSoleCheckbox.isSelected()) {
            services.append("Renew Sole, ");
        }
        if (repairCheckbox.isSelected()) {
            services.append("Repair, ");
        }
        if (customPaintCheckbox.isSelected()) {
            services.append("Custom Paint, ");
        }

        if (services.length() > 0) {
            services.setLength(services.length() - 2);
        }

        return services.toString();

    }

    private String getShoesType() {
        return typeCmb.getSelectedItem().toString();
    }

    private boolean isFill() {
        if (ticketIdTxt.getText().trim().isEmpty()
                || customerNameTxt.getText().trim().isEmpty()
                || brandTxt.getText().trim().isEmpty()
                || modelTxt.getText().trim().isEmpty()
                || colorTxt.getText().trim().isEmpty()
                || laborPriceTxt.getText().trim().isEmpty()
                || voucherTxt.getText().trim().isEmpty()) {
            return false;
        }
        return true;
    }

    private void clearForm() {
        ticketIdTxt.setText("");
        customerNameTxt.setText("");
        brandTxt.setText("");
        modelTxt.setText("");
        colorTxt.setText("");
        laborPriceTxt.setText("");
        typeCmb.setSelectedIndex(0);
        washingCheckbox.setSelected(false);
        renewUpperCheckbox.setSelected(false);
        renewSoleCheckbox.setSelected(false);
        repairCheckbox.setSelected(false);
        customPaintCheckbox.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoesServicesTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoesServicesTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoesServicesTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoesServicesTicketFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoesServicesTicketFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JCheckBox customPaintCheckbox;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JPanel fillPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laborPriceLabel;
    private javax.swing.JTextField laborPriceTxt;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JButton printBtn;
    private javax.swing.JCheckBox renewSoleCheckbox;
    private javax.swing.JCheckBox renewUpperCheckbox;
    private javax.swing.JCheckBox repairCheckbox;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JLabel ticketIdLabel;
    private javax.swing.JTextField ticketIdTxt;
    private javax.swing.JTextArea ticketInfoTxtArea;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JPanel ticketInformationPanel;
    private javax.swing.JComboBox<String> typeCmb;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JTextField voucherTxt;
    private javax.swing.JCheckBox washingCheckbox;
    // End of variables declaration//GEN-END:variables
}
